export const iconKeywords: Record<string, string[]> = {
  // Food & Dining
  'utensils': ['food', 'eat', 'restaurant', 'dining', 'meal', 'lunch', 'dinner'],
  'utensils-crossed': ['food', 'eat', 'restaurant', 'dining', 'meal', 'kitchen'],
  'coffee': ['cup', 'tea', 'drink', 'hot', 'beverage', 'mug', 'cafe', 'latte'],
  'pizza': ['food', 'fast food', 'slice', 'italian', 'snack'],
  'sandwich': ['food', 'lunch', 'snack', 'bread', 'sub'],
  'wine': ['drink', 'alcohol', 'glass', 'bar', 'party'],
  'beer': ['drink', 'alcohol', 'bar', 'pub', 'party', 'pint'],
  'soup': ['food', 'hot', 'bowl', 'stew', 'broth'],
  'cooking-pot': ['food', 'cook', 'kitchen', 'pot', 'stew'],
  'apple': ['fruit', 'food', 'healthy', 'snack'],
  'cherry': ['fruit', 'food', 'berry'],
  'grape': ['fruit', 'food', 'wine'],
  'banana': ['fruit', 'food', 'snack'],
  'carrot': ['vegetable', 'food', 'healthy'],
  'beef': ['meat', 'food', 'steak', 'protein'],
  'fish': ['seafood', 'food', 'protein', 'ocean'],
  'egg': ['food', 'breakfast', 'protein'],
  'milk': ['drink', 'dairy', 'breakfast'],
  'ice-cream': ['dessert', 'sweet', 'frozen', 'treat', 'gelato'],
  'croissant': ['bread', 'pastry', 'breakfast', 'bakery', 'french'],
  'salad': ['food', 'healthy', 'vegetable', 'green', 'diet'],
  'cookie': ['snack', 'sweet', 'dessert', 'biscuit', 'treat'],
  'cake': ['dessert', 'sweet', 'birthday', 'bakery', 'celebration'],
  'cake-slice': ['dessert', 'sweet', 'birthday', 'bakery', 'pie'],
  'candy': ['sweet', 'sugar', 'snack', 'treat'],
  'popcorn': ['snack', 'movie', 'cinema', 'theater'],
  'wheat': ['grain', 'bread', 'farm', 'cereal'],
  'citrus': ['fruit', 'orange', 'lemon', 'lime'],
  'leafy-green': ['vegetable', 'salad', 'healthy', 'green'],

  // Transport
  'car': ['vehicle', 'drive', 'auto', 'ride', 'commute', 'transport'],
  'car-front': ['vehicle', 'drive', 'auto', 'ride', 'commute'],
  'bus': ['transport', 'public', 'commute', 'transit', 'travel'],
  'train': ['transport', 'rail', 'commute', 'transit', 'metro', 'subway'],
  'tram-front': ['transport', 'rail', 'commute', 'transit', 'streetcar'],
  'plane': ['flight', 'travel', 'air', 'trip', 'vacation', 'airport'],
  'plane-takeoff': ['flight', 'travel', 'departure', 'airport'],
  'plane-landing': ['flight', 'travel', 'arrival', 'airport'],
  'bike': ['bicycle', 'cycle', 'ride', 'exercise', 'commute'],
  'ship': ['boat', 'cruise', 'travel', 'sea', 'ocean', 'ferry'],
  'sailboat': ['boat', 'sail', 'sea', 'ocean', 'yacht'],
  'fuel': ['gas', 'petrol', 'diesel', 'station', 'pump'],
  'parking-circle': ['park', 'car', 'garage', 'lot'],
  'truck': ['vehicle', 'delivery', 'freight', 'moving', 'hauling'],
  'ambulance': ['emergency', 'hospital', 'medical', 'health'],
  'navigation': ['gps', 'direction', 'navigate', 'location'],
  'map-pin': ['location', 'place', 'gps', 'address', 'marker'],
  'map': ['navigation', 'direction', 'location', 'travel'],
  'compass': ['direction', 'navigation', 'explore', 'travel'],
  'route': ['direction', 'path', 'travel', 'road', 'way'],

  // Shopping
  'shopping-cart': ['buy', 'purchase', 'store', 'shop', 'cart', 'basket', 'grocery'],
  'shopping-bag': ['buy', 'purchase', 'store', 'shop', 'bag', 'retail'],
  'package': ['delivery', 'box', 'parcel', 'shipping', 'order'],
  'package-open': ['delivery', 'unbox', 'parcel', 'shipping'],
  'tag': ['price', 'label', 'sale', 'discount'],
  'tags': ['price', 'label', 'sale', 'discount'],
  'store': ['shop', 'retail', 'market', 'buy'],
  'shirt': ['clothes', 'clothing', 'fashion', 'apparel', 'wear'],
  'watch': ['time', 'accessory', 'wrist', 'jewelry', 'luxury'],
  'gem': ['jewelry', 'diamond', 'luxury', 'precious', 'ring'],
  'crown': ['royal', 'king', 'queen', 'luxury', 'premium'],
  'gift': ['present', 'birthday', 'celebration', 'surprise', 'wrap'],
  'percent': ['discount', 'sale', 'off', 'deal', 'savings'],
  'badge-percent': ['discount', 'coupon', 'sale', 'deal', 'offer'],

  // Finance
  'wallet': ['money', 'cash', 'payment', 'finance', 'purse'],
  'landmark': ['bank', 'government', 'institution', 'building'],
  'banknote': ['money', 'cash', 'bill', 'payment', 'currency'],
  'receipt': ['bill', 'invoice', 'payment', 'purchase', 'transaction'],
  'piggy-bank': ['savings', 'money', 'save', 'bank', 'deposit'],
  'trending-up': ['profit', 'growth', 'increase', 'stock', 'investment'],
  'trending-down': ['loss', 'decline', 'decrease', 'stock'],
  'hand-coins': ['money', 'payment', 'donate', 'tip', 'charity'],
  'coins': ['money', 'cash', 'change', 'currency'],
  'circle-dollar-sign': ['money', 'dollar', 'currency', 'price', 'cost'],
  'credit-card': ['payment', 'card', 'bank', 'debit', 'swipe', 'visa'],
  'calculator': ['math', 'calculate', 'compute', 'numbers', 'accounting'],
  'arrow-up-circle': ['increase', 'up', 'income', 'profit'],
  'arrow-down-circle': ['decrease', 'down', 'expense', 'loss'],

  // Home & Utilities
  'house': ['home', 'residence', 'property', 'real estate', 'rent', 'mortgage'],
  'building': ['office', 'work', 'apartment', 'commercial'],
  'building-2': ['office', 'work', 'apartment', 'commercial', 'tower'],
  'lightbulb': ['idea', 'electricity', 'light', 'power', 'utility'],
  'zap': ['electricity', 'power', 'energy', 'lightning', 'charge'],
  'droplet': ['water', 'utility', 'liquid', 'rain'],
  'droplets': ['water', 'utility', 'rain', 'shower'],
  'flame': ['fire', 'gas', 'heat', 'hot', 'energy'],
  'wind': ['air', 'breeze', 'weather', 'fan'],
  'wifi': ['internet', 'network', 'wireless', 'connection', 'broadband'],
  'phone': ['call', 'telephone', 'mobile', 'bill'],
  'smartphone': ['mobile', 'cell', 'device', 'app'],
  'tv': ['television', 'screen', 'entertainment', 'streaming'],
  'monitor': ['screen', 'computer', 'display', 'desktop'],
  'laptop': ['computer', 'work', 'device', 'notebook'],
  'gamepad-2': ['game', 'gaming', 'play', 'console', 'controller'],
  'plug': ['electricity', 'power', 'charge', 'outlet'],
  'cable': ['wire', 'connection', 'charge', 'cord'],
  'thermometer': ['temperature', 'heat', 'weather', 'fever'],
  'air-vent': ['ac', 'cooling', 'heating', 'hvac', 'ventilation'],
  'bath': ['bathroom', 'shower', 'wash', 'hygiene', 'tub'],
  'bed-double': ['sleep', 'bedroom', 'rest', 'hotel', 'mattress'],
  'sofa': ['couch', 'furniture', 'living room', 'lounge', 'seat'],
  'lamp': ['light', 'desk', 'table', 'reading'],
  'door-open': ['entrance', 'exit', 'room', 'entry'],
  'key': ['lock', 'access', 'security', 'house'],
  'lock': ['security', 'safe', 'password', 'protect'],
  'shield-check': ['security', 'protect', 'safe', 'verified'],
  'shield': ['security', 'protect', 'safe', 'defense'],

  // Health & Wellness
  'heart': ['love', 'health', 'like', 'favorite', 'care'],
  'heart-pulse': ['health', 'medical', 'heartbeat', 'vital', 'cardio'],
  'activity': ['fitness', 'exercise', 'health', 'workout', 'pulse'],
  'pill': ['medicine', 'drug', 'pharmacy', 'health', 'tablet'],
  'stethoscope': ['doctor', 'medical', 'health', 'checkup', 'clinic'],
  'syringe': ['injection', 'medical', 'vaccine', 'health'],
  'bandaid': ['injury', 'medical', 'first aid', 'wound', 'bandage'],
  'hospital': ['medical', 'health', 'doctor', 'clinic', 'emergency'],
  'cross': ['medical', 'health', 'first aid', 'plus'],
  'brain': ['mind', 'think', 'mental', 'intelligence', 'psychology'],
  'dumbbell': ['gym', 'exercise', 'fitness', 'workout', 'strength'],
  'person-standing': ['person', 'body', 'standing', 'human'],
  'footprints': ['walk', 'steps', 'hiking', 'track'],
  'glasses': ['vision', 'eye', 'reading', 'spectacles', 'optical'],
  'smile': ['happy', 'emotion', 'face', 'joy'],
  'moon': ['night', 'sleep', 'dark', 'evening'],
  'sun': ['day', 'bright', 'weather', 'morning', 'light'],
  'umbrella': ['rain', 'weather', 'protection', 'wet'],

  // Entertainment
  'music': ['song', 'audio', 'tune', 'melody', 'listen'],
  'music-2': ['song', 'audio', 'tune', 'melody', 'note'],
  'headphones': ['audio', 'listen', 'music', 'earphones', 'podcast'],
  'film': ['movie', 'cinema', 'video', 'theater', 'watch'],
  'clapperboard': ['movie', 'cinema', 'film', 'action', 'director'],
  'camera': ['photo', 'picture', 'photography', 'snap', 'capture'],
  'image': ['photo', 'picture', 'gallery', 'art'],
  'palette': ['art', 'paint', 'color', 'design', 'creative'],
  'brush': ['art', 'paint', 'draw', 'creative'],
  'scissors': ['cut', 'craft', 'trim', 'tool'],
  'sparkles': ['magic', 'special', 'new', 'shine', 'glitter'],
  'party-popper': ['celebration', 'birthday', 'event', 'party', 'confetti'],
  'drama': ['theater', 'acting', 'performance', 'show', 'masks'],
  'ticket': ['event', 'movie', 'concert', 'show', 'admission', 'pass'],
  'dice-5': ['game', 'gambling', 'luck', 'casino', 'chance'],
  'puzzle': ['game', 'brain', 'solve', 'challenge'],
  'blocks': ['toy', 'build', 'play', 'lego'],
  'radio': ['broadcast', 'audio', 'listen', 'fm', 'station'],
  'mic': ['microphone', 'sing', 'speak', 'podcast', 'record'],

  // Education & Work
  'book': ['read', 'study', 'library', 'literature', 'novel'],
  'book-open': ['read', 'study', 'library', 'learning'],
  'book-marked': ['read', 'bookmark', 'favorite', 'saved'],
  'notebook': ['notes', 'write', 'journal', 'study', 'diary'],
  'notebook-pen': ['notes', 'write', 'journal', 'study'],
  'graduation-cap': ['education', 'school', 'university', 'degree', 'college'],
  'school': ['education', 'learn', 'building', 'class', 'tuition'],
  'file-text': ['document', 'file', 'paper', 'text', 'report'],
  'briefcase': ['work', 'job', 'business', 'office', 'career'],
  'badge-check': ['verified', 'approved', 'certified', 'complete'],
  'award': ['achievement', 'prize', 'winner', 'ribbon'],
  'trophy': ['achievement', 'winner', 'prize', 'champion', 'award'],
  'medal': ['achievement', 'winner', 'prize', 'sports'],
  'target': ['goal', 'aim', 'bullseye', 'objective'],
  'pen-tool': ['design', 'write', 'draw', 'creative'],
  'ruler': ['measure', 'tool', 'size', 'length'],
  'presentation': ['slides', 'meeting', 'work', 'office', 'powerpoint'],
  'newspaper': ['news', 'press', 'media', 'article', 'read'],

  // Pets & Animals
  'paw-print': ['pet', 'animal', 'dog', 'cat', 'vet'],
  'cat': ['pet', 'animal', 'kitten', 'feline'],
  'dog': ['pet', 'animal', 'puppy', 'canine'],
  'bird': ['animal', 'fly', 'pet', 'nature', 'tweet'],
  'bug': ['insect', 'pest', 'nature', 'ant'],
  'rabbit': ['pet', 'animal', 'bunny', 'easter'],
  'squirrel': ['animal', 'nature', 'nut', 'wildlife'],
  'snail': ['slow', 'animal', 'shell', 'nature'],
  'turtle': ['animal', 'slow', 'shell', 'nature', 'pet'],

  // Nature & Outdoors
  'trees': ['nature', 'forest', 'park', 'outdoor', 'green'],
  'tree-deciduous': ['nature', 'tree', 'park', 'outdoor'],
  'tree-pine': ['nature', 'tree', 'christmas', 'forest', 'evergreen'],
  'flower': ['nature', 'plant', 'garden', 'bloom', 'floral'],
  'flower-2': ['nature', 'plant', 'garden', 'bloom'],
  'sprout': ['plant', 'grow', 'seed', 'garden', 'nature'],
  'clover': ['luck', 'nature', 'plant', 'irish'],
  'leaf': ['nature', 'plant', 'green', 'tree', 'eco'],
  'mountain': ['nature', 'hiking', 'outdoor', 'climb', 'adventure'],
  'mountain-snow': ['nature', 'skiing', 'winter', 'cold', 'alpine'],
  'waves': ['water', 'ocean', 'sea', 'beach', 'surf'],
  'tent': ['camping', 'outdoor', 'adventure', 'hike', 'nature'],
  'campfire': ['camping', 'fire', 'outdoor', 'bonfire', 'nature'],
  'flashlight': ['light', 'dark', 'camping', 'torch'],
  'backpack': ['travel', 'school', 'hiking', 'bag', 'adventure'],
  'luggage': ['travel', 'trip', 'suitcase', 'vacation', 'bag'],
  'globe': ['world', 'earth', 'travel', 'international', 'global'],
  'earth': ['world', 'planet', 'global', 'environment'],
  'sunrise': ['morning', 'dawn', 'early', 'sun'],
  'sunset': ['evening', 'dusk', 'sun', 'twilight'],
  'cloud': ['weather', 'sky', 'storage', 'overcast'],
  'snowflake': ['winter', 'cold', 'snow', 'ice', 'frozen'],
  'star': ['favorite', 'rating', 'night', 'sky', 'review'],
  'sparkle': ['shine', 'glitter', 'special', 'magic'],

  // Communication
  'message-circle': ['chat', 'text', 'sms', 'talk', 'conversation'],
  'message-square': ['chat', 'text', 'sms', 'talk', 'comment'],
  'mail': ['email', 'letter', 'inbox', 'message', 'postal'],
  'send': ['message', 'share', 'submit', 'deliver'],
  'bell': ['notification', 'alert', 'alarm', 'ring', 'reminder'],
  'bell-ring': ['notification', 'alert', 'alarm', 'ringing'],
  'megaphone': ['announce', 'broadcast', 'marketing', 'promotion', 'loud'],

  // People & Social
  'users': ['people', 'group', 'team', 'community', 'friends'],
  'user': ['person', 'profile', 'account', 'individual'],
  'baby': ['child', 'infant', 'kid', 'newborn', 'family'],
  'handshake': ['deal', 'agreement', 'business', 'partner', 'contract'],
  'heart-handshake': ['charity', 'donate', 'help', 'support', 'care'],
  'thumbs-up': ['like', 'approve', 'good', 'agree', 'positive'],

  // Tech
  'code': ['programming', 'developer', 'software', 'coding', 'tech'],
  'terminal': ['command', 'console', 'shell', 'programming'],
  'database': ['data', 'storage', 'server', 'backend'],
  'server': ['hosting', 'cloud', 'backend', 'network'],
  'cpu': ['processor', 'computer', 'hardware', 'chip'],
  'printer': ['print', 'paper', 'document', 'office'],
  'qr-code': ['scan', 'barcode', 'digital', 'payment'],

  // Miscellaneous
  'clock': ['time', 'hour', 'schedule', 'watch'],
  'timer': ['countdown', 'time', 'stopwatch', 'alarm'],
  'hourglass': ['time', 'wait', 'loading', 'patience', 'sand'],
  'alarm': ['wake', 'time', 'morning', 'reminder', 'alert'],
  'repeat': ['loop', 'cycle', 'recurring', 'subscription', 'again'],
  'circle-dot': ['record', 'dot', 'target', 'radio'],
  'circle': ['round', 'shape', 'dot'],
  'shapes': ['geometry', 'form', 'design', 'pattern'],
  'flag': ['country', 'mark', 'milestone', 'report'],
  'bookmark': ['save', 'favorite', 'mark', 'read later'],
  'pin': ['location', 'attach', 'mark', 'important'],
  'paperclip': ['attach', 'document', 'file', 'clip'],
  'link': ['url', 'chain', 'connect', 'web'],
  'anchor': ['marine', 'ship', 'dock', 'port'],
  'wrench': ['tool', 'fix', 'repair', 'maintenance', 'settings'],
  'hammer': ['tool', 'build', 'construct', 'fix', 'repair'],
  'paintbrush': ['art', 'paint', 'draw', 'creative', 'design'],
  'box': ['package', 'container', 'storage', 'ship'],
  'archive': ['storage', 'backup', 'save', 'old'],
  'inbox': ['mail', 'message', 'receive', 'tray'],
  'settings': ['config', 'gear', 'preferences', 'options', 'setup'],
  'cog': ['settings', 'gear', 'config', 'preferences'],
  'help-circle': ['help', 'question', 'support', 'faq', 'info'],
  'info': ['information', 'details', 'about', 'help'],
  'alert-circle': ['warning', 'error', 'caution', 'attention'],
  'verified': ['check', 'approved', 'authentic', 'trusted'],
};
